- JOB: "intercept -g $DEVNODE | caps2esc |space2meta| uinput -d $DEVNODE"
  DEVICE:
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_ESC, KEY_SPACE]



# - JOB: "intercept -g $DEVNODE |caps2esc| dual-function-keys -c /etc/interception/dual-function-keys/my-mappings.yaml | uinput -d $DEVNODE"
#   DEVICE:
#     EVENTS:
#       EV_KEY: [KEY_A, KEY_S, KEY_D, KEY_F, KEY_LEFTSHIFT, KEY_LEFTCTRL, KEY_LEFTALT, KEY_LEFTMETA, KEY_CAPSLOCK, KEY_ESC]
